apiVersion: batch/v1
kind: Job
metadata:
  name: acord-dac-cicd-test
  labels:
    jobgroup: acorn-dac-cicd
spec:
  template:
    spec:
      containers:
      - name: acord-dac-cicd-2023-2
        image:  ghcr.io/ben-hawks/acord-dac-cicd/acord-dac-cicd:v2023.2
        terminationMessagePolicy: FallbackToLogsOnError
        env:
          - name: LD_PRELOAD
            value: /lib/x86_64-linux-gnu/libudev.so.1
        args:
          - -l
          - -c
          - >-
              cat /home/runner/.bashrc &&
              source /venv/bin/activate && 
              echo "activated venv" &&
              source /home/runner/.bashrc &&
              echo "Setup Vitis, running job..." &&
              source firmware/targets/test_kv260/CreatePetalinuxProject.sh
        volumeMounts:
        - name: amd-xilinx-tools
          mountPath: /opt/Xilinx
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 64Gi
            cpu: "4"
          requests:
            memory: 64Gi
            cpu: "4"
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        command: ["/bin/sh"]
        args:
          - -l
          - -c
          - >-
              if cd /opt/repo/zCCM_fw; 
              then git pull; 
              else git clone https://github.com/awhitbeck/zCCM_fw -b main /opt/repo/zCCM_fw;
              fi
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
        resources:
          limits:
            memory: 8Gi
            cpu: "2"
          requests:
            memory: 8Gi
            cpu: "2"
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
      volumes:
      - name: amd-xilinx-tools
        persistentVolumeClaim:
          claimName: amd-xilinx-tools
      - name: git-repo
        emptyDir:
          sizeLimit: 5Gi
  backoffLimit: 5