apiVersion: batch/v1
kind: Job
metadata:
  name: acord-dac-cicd-test
  labels:
    jobgroup: acorn-dac-cicd
spec:
  template:
    spec:
      containers:
      - name: acord-dac-cicd-2023-2
        image:  adregistry.fnal.gov/dac/acorn-dac-cicd:v2023.2
        terminationMessagePolicy: FallbackToLogsOnError
        env:
          - name: LD_PRELOAD
            value: /lib/x86_64-linux-gnu/libudev.so.1
        command: ["sh","-l", "-c", "echo 'Interactive Pod, waiting for login' && sleep infinity"]
        volumeMounts:
        - name: amd-xilinx-tools
          mountPath: /opt/Xilinx
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 64Gi
            cpu: "4"
          requests:
            memory: 64Gi
            cpu: "4"
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
      volumes:
      - name: amd-xilinx-tools
        persistentVolumeClaim:
          claimName: amd-xilinx-tools
      - name: git-repo
        emptyDir:
          sizeLimit: 5Gi
      imagePullSecrets:
        - name: bhawks-dac-robot
      restartPolicy:
        OnFailure
  backoffLimit: 5
