apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: amd-xilinx-tools
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 500Gi